
# ---- Register User ----
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Rahman",
  "email": "rahman@example.com",
  "password": "123456"
}

###

# ---- Login User----
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "noyon@example.com",
  "password": "123456"
}

###

GET http://localhost:5000/api/auth/me
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWQ0YjJhYjYxN2JlOWEyMWEyYTU2ZjAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDg0NDg0NjJ9.yg6DVNLRTHKtw9YbPUIBARWSSDDmzNFNRAX-j3z1cfE