
# ---- Register User ----
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Noyon",
  "email": "noyon@example.com",
  "password": "123456"
}

###

# ---- Login User----
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "noyon@example.com",
  "password": "123456"
}

###

GET http://localhost:5000/api/auth/me
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWZjMGI5ZmRhODgxY2VmOTVmZmQ1YTIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNzExMDE2OTI1fQ.Ny1L2mZCkVNfMdcyk_O-5Kq0QB5EmPqRqLdntP6sMiA