# ---- Get Home ----
GET http://localhost:5000

###

# ---- Get Generes ----
GET http://localhost:5000/api/genres

###

# ---- Get a spefic Genre by Id ----
GET http://localhost:5000/api/genres/65cd13bb24420bb8b58dca17

###

# ---- Create Genere ----
POST http://localhost:5000/api/genres
Content-Type: application/json
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWZjMGQ2YWNkNDVlN2NjNzczZDQ2ZDIiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MTEwMTc1MDd9.6hdvRKvVQVMiAFvEtrCiXFK3HKZoAv37H8YsPkVe4aU

{
  "name": "Animation"
}

###

# ---- Update a spefic Genre by Id ----
PUT http://localhost:5000/api/genres/65cd154dd40bf03952e2c994
Content-Type: application/json

{
  "name": "Animation"
}

###

# ---- Delete a spefic Genre by Id ----
DELETE http://localhost:5000/api/genres/65d4c478a9ec72ba11bccb5e
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NWQ0YjJhYjYxN2JlOWEyMWEyYTU2ZjAiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE3MDg0NDg0NjJ9.yg6DVNLRTHKtw9YbPUIBARWSSDDmzNFNRAX-j3z1cfE